version: '3'
services:
  configuration-service:
    build:
      context: ./configuration-service/
      args:
        JAR_FILE: ./target/configuration-service-1.0.jar
    ports:
      - "8888:8888"
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
    restart: on-failure

  eureka-service:
    build:
      context: ./eureka-service/
      args:
        JAR_FILE: ./target/eureka-service-1.0.jar
    ports:
      - "8761:8761"
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
    restart: on-failure
    depends_on:
      - configuration-service
    links:
      - configuration-service