version: '3'
services:
  configuration-service:
    build:
      context: ./configuration-service/
      args:
        JAR_FILE: ./target/configuration-service-1.0.jar
    ports:
      - "8888:8888"
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888"]
      interval: 30s
      timeout: 10s
      retries: 5

  eureka-service:
    build:
      context: ./eureka-service/
      args:
        JAR_FILE: ./target/eureka-service-1.0.jar
    ports:
      - "8761:8761"
    restart: on-failure
    depends_on:
      - configuration-service
    links:
      - configuration-service