version: '3'
services:
  configuration-service:
    build:
      context: ./configuration-service/
      args:
        JAR_FILE: ./target/configuration-service-1.0.jar
    ports:
      - "8888:8888"
    environment:
      - "SPRING_PROFILES_ACTIVE=standalone"
    restart: on-failure